# Vertical Candidate List
Vertical Candidate List=False
# Use mouse wheel to go to prev or next page
WheelForPaging=True
# Font (larger CJK font)
Font="Noto Sans CJK SC 14"
# Menu Font
MenuFont="Noto Sans CJK SC 12"
# Tray Font
TrayFont="Noto Sans CJK SC 11"
# Prefer Text Icon
PreferTextIcon=False
# Show Layout Name In Icon
ShowLayoutNameInIcon=True
# Use Per Screen DPI on X11
PerScreenDPI=True
# Enable fractional scale under Wayland
EnableFractionalScale=True
# Theme
Theme=elegant
# Dark Theme (used when following system dark mode)
DarkTheme=default-dark
# Follow system light/dark color scheme
UseDarkTheme=False
